// <auto-generated />
using Invoice.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoice.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240815131704_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invoice.Models.Bill", b =>
                {
                    b.Property<string>("BillNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BillNo");

                    b.HasIndex("PartyName");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            BillNo = "B001",
                            PartyName = "The Bread Basket"
                        },
                        new
                        {
                            BillNo = "B002",
                            PartyName = "Sweet Tooth Supply"
                        },
                        new
                        {
                            BillNo = "B003",
                            PartyName = "Sweet Tooth Supply"
                        },
                        new
                        {
                            BillNo = "B004",
                            PartyName = "The Bread Basket"
                        });
                });

            modelBuilder.Entity("Invoice.Models.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HSNCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Particular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("SNO")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillNo");

                    b.ToTable("BillItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 40.0,
                            BillNo = "B001",
                            HSNCode = "21436587",
                            Particular = "Cake",
                            Quantity = 2,
                            Rate = 20.0,
                            SNO = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 50.0,
                            BillNo = "B001",
                            HSNCode = "26843715",
                            Particular = "Apple Pie",
                            Quantity = 1,
                            Rate = 50.0,
                            SNO = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 40.0,
                            BillNo = "B001",
                            HSNCode = "43219876",
                            Particular = "Cola",
                            Quantity = 1,
                            Rate = 40.0,
                            SNO = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 40.0,
                            BillNo = "B002",
                            HSNCode = "21436587",
                            Particular = "Cake",
                            Quantity = 2,
                            Rate = 20.0,
                            SNO = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 50.0,
                            BillNo = "B002",
                            HSNCode = "26843715",
                            Particular = "Apple Pie",
                            Quantity = 1,
                            Rate = 50.0,
                            SNO = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 40.0,
                            BillNo = "B003",
                            HSNCode = "21436587",
                            Particular = "Cake",
                            Quantity = 2,
                            Rate = 20.0,
                            SNO = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 50.0,
                            BillNo = "B003",
                            HSNCode = "26843715",
                            Particular = "Apple Pie",
                            Quantity = 1,
                            Rate = 50.0,
                            SNO = 2
                        },
                        new
                        {
                            Id = 8,
                            Amount = 40.0,
                            BillNo = "B003",
                            HSNCode = "43219876",
                            Particular = "Cola",
                            Quantity = 1,
                            Rate = 40.0,
                            SNO = 3
                        },
                        new
                        {
                            Id = 9,
                            Amount = 30.0,
                            BillNo = "B003",
                            HSNCode = "94712586",
                            Particular = "Ice Cream",
                            Quantity = 2,
                            Rate = 15.0,
                            SNO = 4
                        },
                        new
                        {
                            Id = 10,
                            Amount = 40.0,
                            BillNo = "B004",
                            HSNCode = "21436587",
                            Particular = "Cake",
                            Quantity = 2,
                            Rate = 20.0,
                            SNO = 1
                        });
                });

            modelBuilder.Entity("Invoice.Models.PartyDetail", b =>
                {
                    b.Property<string>("PartyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartyName");

                    b.ToTable("PartyDetails");

                    b.HasData(
                        new
                        {
                            PartyName = "Sweet Tooth Supply",
                            Address = "1234 Maple Street, Anytown, CA, 12345, USA",
                            GSTNumber = "27ABACB5678H1Z5"
                        },
                        new
                        {
                            PartyName = "The Bread Basket",
                            Address = "5678 Oak Avenue, Springfield, NY, 54321, USA",
                            GSTNumber = "36AAAC0001AB1Z5"
                        });
                });

            modelBuilder.Entity("Invoice.Models.Bill", b =>
                {
                    b.HasOne("Invoice.Models.PartyDetail", "PartyDetail")
                        .WithMany()
                        .HasForeignKey("PartyName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyDetail");
                });

            modelBuilder.Entity("Invoice.Models.BillItem", b =>
                {
                    b.HasOne("Invoice.Models.Bill", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("BillNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Invoice.Models.Bill", b =>
                {
                    b.Navigation("BillItems");
                });
#pragma warning restore 612, 618
        }
    }
}
